kind: pipeline
name: default

steps:
- name: test
  image: node
  environment:
    MONGODB_URI: mongodb://db:27017/notes
  commands:
  - npm install
  - npm test

- name: deploy
  image: ryanmehta/drone-heroku
  settings:
    email: ryan.mehta@gmail.com
    token:
      from_secret: token
    app: alchemy-notes

services:
- name: db
  image: mongo
