kind: pipeline
name: default

steps:
- name: test
  image: node
  commands:
  - npm install
  - npm test

- name: deploy
  image: ryanmehta/drone-heroku
  settings:
    email: ryan.mehta@gmail.com
    token:
      from_secret: token
    app: alchemy-notes
